# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export DOTFILES="$(dirname $(dirname $(readlink ~/.bash_profile)))"

test -f ~/.config/bash/.bash_aliases && . ~/.config/bash/.bash_aliases
test -f ~/.config/bash/.bash_completions && . ~/.config/bash/.bash_completions
