"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "alphabetical"
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[opener]
folder = [{ run = 'nvim "$@"', block = true, desc = "neovim", for = "linux" }]

text = [
	{ run = 'nvim "$@"', block = true, desc = "$EDITOR", for = "linux" },
	{ run = 'nvim "$@"', block = true, desc = "neovim", for = "linux" },
]

document = [
	{ run = 'wslview "$@"', orphan = true, desc = "wslview", for = "linux" },
	{ run = 'libreoffice "$@"', orphan = true, desc = "libreoffice", for = "linux" },
]

image = [
	{ run = 'wslview "$@"', orphan = true, desc = "wslview", for = "linux" },
]
video = [
	{ run = 'wslview "$@"', orphan = true, desc = "wslview", for = "linux" },
]
audio = [
	{ run = 'wslview "$@"', orphan = true, desc = "wslview", for = "linux" },
]
fallback = [
	{ run = 'wslview "$@"', orphan = true, desc = "wslview", for = "linux" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "application/octet-stream", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },
	{ mime = "application/json", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },
	{ mime = "application/pdf", use = "document" },
	{ mime = "application/epub+zip", use = "document" },
	{ mime = "application/x-mobipocket-ebook", use = "document" },

	{ mime = "*", use = "fallback" },
]

[preview]
wrap = "yes"
tab_size = 2
max_width = 1200
max_height = 1800

[plugin]
prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
]

prepend_previewers = [
	{ name = "*.csv", run = "rich-preview" },   # for csv files
	{ name = "*.md", run = "rich-preview" },    # for markdown (.md) files
	{ name = "*.rst", run = "rich-preview" },   # for restructured text (.rst) files
	{ name = "*.ipynb", run = "rich-preview" }, # for jupyter notebooks (.ipynb)
	{ name = "*.json", run = "rich-preview" },  # for json (.json) files
	#    { name = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
]
